test_code_coverage:
  stage: test
  rules:
    - if: $CI_COMMIT_TITLE =~ /-no_tests$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: python:latest
  script:
    - pip install civilpy[dev]
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pypi_publish:
  stage: deploy
  cache: {}
  only:
    - master
  image: python:latest
  script:
    - pip install -U build twine
    - python setup.py sdist
    - twine upload dist/*

gitlab_publish:
  stage: deploy
  cache: {}
  only:
    - master
  image: python:latest
  script:
    - pip install build twine
    - python -m build
    - twine upload --repository civilpy-gitlab --verbose --non-interactive dist/*

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r civilpy/webpages/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

verify-3.8:
    extends: test_code_coverage
    stage: test
    image: python:3.8

verify-3.9:
    extends: test_code_coverage
    stage: test
    image: python:3.9