test_code_coverage:
  stage: test
  rules:
    - if: $CI_COMMIT_TITLE =~ /-no_tests$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: python:latest
  script:
    - pip install civilpy[dev]
    - coverage run -m pytest
    - coverage json

pypi_publish:
  stage: deploy
  only:
    - master
  image: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://pypi.org/project/civilpy/ dist/*

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r civilpy/webpages/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

verify-3.8:
    extends: test_code_coverage
    stage: test
    image: python:3.8

verify-3.9:
    extends: test_code_coverage
    stage: test
    image: python:3.9