build-package:
  stage: deploy
  only:
    changes:
      - setup.py
  image: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r civilpy/webpages/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

verify-3.6:
    extends: "deploy"
    stage: "verify"
    image: "python:3.6"

verify-3.7:
    extends: "deploy"
    stage: "verify"
    image: "python:3.7"

verify-3.8:
    extends: "deploy"
    stage: "verify"
    image: "python:3.8"

verify-3.9:
    extends: "deploy"
    stage: "verify"
    image: "python:3.9"