build-package:
  stage: deploy
  image: python:3.7
  before_script:
    - python3 -m pip install --upgrade twine
    - python3 -m pip install --upgrade build
    - cat $PYPIRC > /tmp/.pypirc
  script:
    - python3 -m build
    - python3 -m twine upload dist/* --config-file /tmp/.pypirc
  only:
    - tags

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r civilpy/webpages/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master