#  CivilPy
#  Copyright (C) 2019-2026 Dane Parks
#
#  SPDX-License-Identifier: MIT
#  See the LICENSE file in the project root for full license text.

"""Write boreholes as a DIGGS 2.5.a document.

The shape follows the files Ohio DOT publishes (gINT -> Keynetix DIGGS
export): one ``Project``, a ``Borehole`` sampling feature per hole with its
own linear referencing system, a ``SamplingActivity`` per sample interval,
``LithologySystem`` observations (SOIL and ROCK), and ``Test`` records for
SPT (``DrivenPenetrationTest`` drive sets), particle size, Atterberg
limits, water content and pocket penetrometer.  Everything written is read
back by :func:`civilpy.geotech.boring_io.parse_diggs`, so a PDF log turned
into DIGGS enters the rest of the library the same way a published DIGGS
file does.

Input is a :class:`~civilpy.geotech.boring.Borehole` or anything with a
``to_borehole()`` (such as ``civilpy.state.ohio.DOT.boring_log_pdf.BoringLog``,
whose sample rows also carry the lab columns the Borehole model does not
hold - those become the ATTERBERG / WATER CONTENT / POCKET PEN tests).
"""

from __future__ import annotations

import datetime as _dt
import re
import uuid
import xml.etree.ElementTree as ET
from pathlib import Path

from civilpy.geotech.boring import Borehole

DIGGS_NS = "http://diggsml.org/schemas/2.5.a"
GML_NS = "http://www.opengis.net/gml/3.2"
XLINK_NS = "http://www.w3.org/1999/xlink"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
CRS = "urn:diggs:def:crs:DIGGS:0.1:4326_5702"      # lon lat (deg) + NAVD88 ft, as ODOT's files
PROPERTY_CS = "urn:x-diggs:def:code-list:property"


def _id(prefix: str, *parts) -> str:
    s = "_".join(str(p) for p in (prefix, *parts) if p not in (None, ""))
    s = re.sub(r"[^A-Za-z0-9_.-]", "-", s)
    return s if re.match(r"^[A-Za-z_]", s) else "_" + s


def _num(v, nd: int = 3) -> str:
    if v is None:
        return ""
    return f"{round(float(v), nd):g}"


class _X:
    """Tiny element builder."""

    def __init__(self, ns=DIGGS_NS):
        self.ns = ns

    def el(self, parent, tag, text=None, *, gml_id=None, ns=None, **attrs):
        e = ET.SubElement(parent, f"{{{ns or self.ns}}}{tag}")
        if gml_id:
            e.set(f"{{{GML_NS}}}id", gml_id)
        for k, v in attrs.items():
            if v is not None:
                e.set(k, str(v))
        if text is not None:
            e.text = str(text)
        return e

    def gml(self, parent, tag, text=None, **attrs):
        return self.el(parent, tag, text, ns=GML_NS, **attrs)

    def ref(self, parent, tag, target):
        e = self.el(parent, tag)
        e.set(f"{{{XLINK_NS}}}href", f"#{target}")
        return e


def _layer_extra(hole_like):
    """Sample rows with lab columns (BoringLog) when available."""
    rows = getattr(hole_like, "samples", None)
    if rows and hasattr(rows[0], "sample_id"):
        return rows
    return []


def build_diggs(holes, *, project: str | None = None, pid: str | None = None, county: str | None = None,
                route: str | None = None, purpose: str | None = None, author: str = "civilpy",
                source: str | None = None, created: str | None = None) -> ET.ElementTree:
    """The DIGGS document as an ElementTree (see :func:`write_diggs`)."""
    ET.register_namespace("", DIGGS_NS)
    ET.register_namespace("gml", GML_NS)
    ET.register_namespace("xlink", XLINK_NS)
    ET.register_namespace("xsi", XSI_NS)
    x = _X()
    root = ET.Element(f"{{{DIGGS_NS}}}Diggs")
    root.set(f"{{{XSI_NS}}}schemaLocation", f"{DIGGS_NS} https://diggsml.org/schemas/2.5.a/Diggs.xsd")
    root.set(f"{{{GML_NS}}}id", "D" + uuid.uuid4().hex)
    created = created or _dt.date.today().isoformat()

    di = x.el(x.el(root, "documentInformation"), "DocumentInformation", gml_id="DI_" + uuid.uuid4().hex[:12])
    x.el(di, "creationDate", created)
    ba = x.el(x.el(di, "author"), "BusinessAssociate", gml_id="BA_author")
    x.gml(ba, "name", author)
    x.el(di, "disclaimer", "Read from the printed boring log; values as printed, sample intervals from the sheet bars.")
    rem = x.el(x.el(di, "auditTrail"), "Remark")
    x.el(rem, "content", f"Generated by civilpy diggs_writer{(' from ' + source) if source else ''}")
    x.el(rem, "remarkDateTime", created)

    holes = list(holes)
    first = holes[0].to_borehole() if holes and hasattr(holes[0], "to_borehole") else (holes[0] if holes else None)
    pname = project or (first.project if first else None) or "project"
    proj_id = _id("Project", pname)
    pr = x.el(x.el(root, "project"), "Project", gml_id=proj_id)
    if pid:
        x.gml(pr, "identifier", pid, codeSpace="ODOT_CS")
    x.gml(pr, "name", pname)
    loc = x.el(x.el(pr, "locality"), "Locality", gml_id=_id("pl", pname))
    if county:
        ad = x.el(x.el(loc, "address"), "Address", gml_id=_id("pla", pname))
        x.el(ad, "county", county)
    if route:
        x.el(loc, "route", route)
    if purpose:
        x.el(pr, "purpose", purpose)

    sf = x.el(root, "samplingFeature")
    sa_root = x.el(root, "samplingActivity")
    obs_root = x.el(root, "observation")
    meas_root = x.el(root, "measurement")

    for hl in holes:
        bh: Borehole = hl.to_borehole() if hasattr(hl, "to_borehole") else hl
        rows = _layer_extra(hl)
        hid = bh.boring_id
        bid, lsr = _id("Borehole", hid), _id(hid, "lsr")
        b = x.el(sf, "Borehole", gml_id=bid)
        x.gml(b, "name", hid)
        x.el(b, "investigationTarget", "Natural Ground")
        x.ref(b, "projectRef", proj_id)
        for name, val in (("Depth to Rock", bh.depth_to_rock_ft), ("Sampling Method", getattr(getattr(hl, "header", None), "sampling_method", None)),
                          ("Reference Alignment", getattr(getattr(hl, "header", None), "alignment", None))):
            p = x.el(x.el(b, "otherSamplingFeatureProperty"), "Parameter", gml_id=_id("obp", hid, name.replace(" ", "")))
            x.el(p, "parameterName", name)
            x.el(p, "parameterValue", _num(val, 2) if isinstance(val, (int, float)) else (val or ""))
        lc = x.el(x.el(b, "locality"), "Locality", gml_id=_id("loc", hid))
        x.el(lc, "station", bh.station or "")
        x.el(lc, "offset", _num(bh.offset_ft, 2), uom="ft")
        x.el(lc, "offsetDirection", bh.offset_direction or "")
        lon, lat, z = bh.longitude, bh.latitude, bh.ground_elevation_ft
        if lon is not None and lat is not None:
            pos = f"{lon:.7f} {lat:.7f}" + (f" {z:.2f}" if z is not None else "")
            dim = 3 if z is not None else 2
            pl = x.el(x.el(b, "referencePoint"), "PointLocation", gml_id=_id(hid, "pl"))
            x.gml(pl, "pos", pos, srsDimension=dim, srsName=CRS, uomLabels="degrees")
            cl = x.el(x.el(b, "centerLine"), "LinearExtent", gml_id=_id(hid, "cl"))
            bottom = f"{lon:.7f} {lat:.7f}" + (f" {z - (bh.total_depth_ft or 0.0):.2f}" if z is not None else "")
            x.gml(cl, "posList", pos + " " + bottom, srsDimension=dim, srsName=CRS, uomLabels="degrees")
        elif z is not None:
            pl = x.el(x.el(b, "referencePoint"), "PointLocation", gml_id=_id(hid, "pl"))
            x.gml(pl, "pos", f"0 0 {z:.2f}", srsDimension=3, srsName=CRS, uomLabels="degrees")
        lr = x.el(x.el(b, "linearReferencing"), "LinearSpatialReferenceSystem", gml_id=lsr)
        x.gml(lr, "identifier", f"urn:x-diggs:def:fi:DIGGSINC:{lsr}", codeSpace="urn:x-def:authority:DIGGSINC")
        x.ref(lr, "linearElement", _id(hid, "cl"))
        lrm = x.el(x.el(lr, "lrm"), "LinearReferencingMethod", gml_id=_id(hid, "lrm"))
        x.el(lrm, "name", "chainage")
        x.el(lrm, "type", "absolute")
        x.el(lrm, "units", "ft")
        if bh.date:
            ti = x.el(x.el(b, "whenConstructed"), "TimeInterval", gml_id=_id("ti", hid))
            x.el(ti, "start", bh.date)
            x.el(ti, "end", getattr(getattr(hl, "header", None), "end", None) or bh.date)
        x.el(b, "totalMeasuredDepth", _num(bh.total_depth_ft, 2), uom="ft")
        x.el(b, "boreholePurpose", bh.purpose or "", codeSpace="ODOT_CS")
        hdr = getattr(hl, "header", None)
        if hdr is not None and getattr(hdr, "drilling_method", None):
            cm = x.el(x.el(b, "constructionMethod"), "BoreholeConstructionMethod", gml_id=_id("cm", hid))
            x.el(cm, "name", "Soil Drill Method")
            sp = x.el(x.el(cm, "constructionMethod"), "Specification", gml_id=_id("cms", hid))
            x.el(sp, "name", hdr.drilling_method)
            x.el(sp, "shortMethodName", "Soil Drill")
            rig = hdr.raw.get("DRILL RIG:") if getattr(hdr, "raw", None) else None
            if rig:
                eq = x.el(x.el(cm, "constructionEquipment"), "Equipment", gml_id=_id("eq", hid))
                x.el(eq, "name", rig)
                x.el(eq, "class", "Drill Rig")
        waters = getattr(hl, "water", None) or ([{"depth_ft": bh.water_strike_depth_ft}] if bh.water_strike_depth_ft is not None else [])
        for k, w in enumerate(waters):
            ws = x.el(x.el(b, "waterStrike"), "WaterStrike", gml_id=_id("ws", hid, k))
            x.el(ws, "status", "1")
            rd = x.el(x.el(ws, "initialWaterStrikeReading"), "WaterStrikeReading", gml_id=_id("wsr", hid, k))
            x.el(rd, "dateTime", bh.date or "")
            pl = x.el(x.el(rd, "waterLocation"), "PointLocation", gml_id=_id("wsl", hid, k))
            x.gml(pl, "pos", _num(w["depth_ft"], 2), srsDimension=1, srsName=f"#{lsr}")

        # samples
        for k, s in enumerate(bh.samples, 1):
            sid = _id("SA", hid, _num(s.depth_top_ft, 2))
            a = x.el(sa_root, "SamplingActivity", gml_id=sid)
            x.gml(a, "name", str(k))
            x.el(a, "investigationTarget", "Natural Ground")
            x.ref(a, "projectRef", proj_id)
            x.ref(a, "samplingFeatureRef", bid)
            le = x.el(x.el(a, "samplingLocation"), "LinearExtent", gml_id=_id("sl", hid, k), srsDimension=1, srsName=f"#{lsr}")
            x.gml(le, "posList", f"{_num(s.depth_top_ft, 2)} {_num(s.depth_bottom_ft, 2)}")
            x.el(a, "activityType", "collect")
            spd = x.el(x.el(a, "sampleProduced"), "SampleProduced", gml_id=_id("SampleProduced", hid, _num(s.depth_top_ft, 2), _num(s.depth_bottom_ft, 2)))
            le2 = x.el(x.el(spd, "location"), "LinearExtent", gml_id=_id("spl", hid, k), srsDimension=1, srsName=f"#{lsr}")
            x.gml(le2, "posList", f"{_num(s.depth_top_ft, 2)} {_num(s.depth_bottom_ft, 2)}")
            sm = x.el(x.el(a, "samplingMethod"), "Specification", gml_id=_id("sm", hid, k))
            x.el(sm, "name", s.method or "", codeSpace="ODOT_CS")
            if s.recovery_in is not None:
                x.el(a, "totalSampleRecoveryLength", _num(s.recovery_in, 2), uom="in")

        # lithology
        for system in ("SOIL", "ROCK"):
            lays = [lay for lay in bh.layers if (lay.system or "SOIL").upper() == system]
            if not lays:
                continue
            ls = x.el(obs_root, "LithologySystem", gml_id=_id("Litho", system.title(), hid))
            x.gml(ls, "name", hid)
            x.ref(ls, "projectRef", proj_id)
            x.ref(ls, "samplingFeatureRef", bid)
            x.el(ls, "lithologyClassificationType", system)
            for lay in lays:
                ob = x.el(x.el(ls, "lithologyObservation"), "LithologyObservation", gml_id=_id("Litho", system.title(), "Observation", hid, _num(lay.depth_top_ft, 2)))
                le = x.el(x.el(ob, "location"), "LinearExtent", gml_id=_id("ll", hid, system, _num(lay.depth_top_ft, 2)), srsName=f"#{lsr}", srsDimension=1)
                x.gml(le, "posList", f"{_num(lay.depth_top_ft, 2)} {_num(lay.depth_bottom_ft, 2)}")
                li = x.el(x.el(ob, "primaryLithology"), "Lithology", gml_id=_id("lith", hid, system, _num(lay.depth_top_ft, 2)))
                x.el(li, "classificationCode", lay.uscs or "", codeSpace="USCS")
                x.el(li, "lithDescription", lay.description or "")
                if lay.color:
                    x.el(x.el(x.el(li, "color"), "Color", gml_id=_id("col", hid, system, _num(lay.depth_top_ft, 2))), "colorName", lay.color)
                for j, con in enumerate(lay.constituents):
                    c = x.el(x.el(li, "constituent"), "Constituent", gml_id=_id("con", hid, system, _num(lay.depth_top_ft, 2), j))
                    x.el(c, "codeValue", con)
                    x.el(c, "abundanceCode", "Major" if j == 0 else "Minor")
                fp = x.el(x.el(li, "fieldProperties"), "FieldProperties", gml_id=_id("fp", hid, system, _num(lay.depth_top_ft, 2)))
                if lay.consistency:
                    x.el(fp, "consistency", lay.consistency)
                if lay.moisture:
                    x.el(fp, "moistureCondition", lay.moisture)
                if lay.rock_strength:
                    x.el(fp, "rockStrength", lay.rock_strength)
                if lay.rock_weathering:
                    x.el(fp, "rockWeathering", lay.rock_weathering)
                if lay.recovery_pct is not None:
                    x.el(fp, "unitRecoveryLength", _num(lay.recovery_pct, 1), uom="%")
                if lay.rqd_pct is not None:
                    x.el(fp, "unitRQDLength", _num(lay.rqd_pct, 1), uom="%")
                p = x.el(x.el(fp, "otherFieldProperty"), "Parameter", gml_id=_id("gr", hid, system, _num(lay.depth_top_ft, 2)))
                x.el(p, "parameterName", "Graphic")
                x.el(p, "parameterValue", lay.classification or "")

        # tests
        hdr_hammer = bh.spt[0].hammer_type if bh.spt else None
        hdr_eff = bh.spt[0].hammer_efficiency if bh.spt else None
        for s in bh.spt:
            t = x.el(meas_root, "Test", gml_id=_id("SPT", hid, _num(s.depth_ft, 2)))
            x.gml(t, "name", "SPT")
            x.el(t, "investigationTarget", "Natural Ground")
            x.ref(t, "projectRef", proj_id)
            x.ref(t, "samplingFeatureRef", bid)
            tr = x.el(x.el(t, "outcome"), "TestResult", gml_id=_id("tr", hid, "spt", _num(s.depth_ft, 2)))
            le = x.el(x.el(tr, "location"), "LinearExtent", gml_id=_id("trl", hid, "spt", _num(s.depth_ft, 2)), srsDimension=1, srsName=f"#{lsr}")
            x.gml(le, "posList", _num(s.depth_ft, 2))
            rs = x.el(x.el(tr, "results"), "ResultSet")
            pp = x.el(x.el(rs, "parameters"), "PropertyParameters", gml_id=_id("pp", hid, "spt", _num(s.depth_ft, 2)))
            pr_ = x.el(x.el(pp, "properties"), "Property", gml_id=_id("prop", hid, "spt", _num(s.depth_ft, 2)), index=1)
            x.el(pr_, "propertyName", "N-Value")
            x.el(pr_, "typeData", "long")
            x.el(pr_, "propertyClass", "n_value", codeSpace="urn:diggs:def:codelist:DIGGS:properties")
            x.el(rs, "dataValues", "" if s.n_value is None else str(s.n_value), cs=",", ts=" ", decimal=".")
            dp = x.el(x.el(t, "procedure"), "DrivenPenetrationTest", gml_id=_id("dpt", hid, _num(s.depth_ft, 2)))
            x.el(dp, "penetrationTestType", "SPT")
            x.el(dp, "hammerType", s.hammer_type or hdr_hammer or "")
            x.el(dp, "hammerEfficiency", s.hammer_efficiency or hdr_eff or "", uom="%")
            x.el(dp, "totalPenetration", _num(s.total_penetration_in, 1), uom="in")
            for j, inc in enumerate(s.increments, 1):
                ds = x.el(x.el(dp, "driveSet"), "DriveSet", gml_id=_id("ds", hid, _num(s.depth_ft, 2), j))
                x.el(ds, "index", str(j))
                x.el(ds, "blowCount", str(inc.blows))
                x.el(ds, "penetration", _num(inc.penetration_in, 1), uom="in")
        for g in bh.grading:
            t = x.el(meas_root, "Test", gml_id=_id("ParticleSize", hid, _num(g.depth_ft, 2)))
            x.gml(t, "name", "PARTICLE_SIZE")
            x.el(t, "investigationTarget", "Natural Ground")
            x.ref(t, "projectRef", proj_id)
            x.ref(t, "samplingFeatureRef", bid)
            tr = x.el(x.el(t, "outcome"), "TestResult", gml_id=_id("tr", hid, "ps", _num(g.depth_ft, 2)))
            le = x.el(x.el(tr, "location"), "LinearExtent", gml_id=_id("trl", hid, "ps", _num(g.depth_ft, 2)), srsDimension=1, srsName=f"#{lsr}")
            x.gml(le, "posList", _num(g.depth_ft, 2))
            ps = x.el(x.el(t, "procedure"), "ParticleSizeTest", gml_id=_id("pst", hid, _num(g.depth_ft, 2)))
            sa = x.el(x.el(ps, "sieveAnalysis"), "SieveAnalysis", gml_id=_id("sa", hid, _num(g.depth_ft, 2)))
            for j, p in enumerate(sorted(g.points, key=lambda p: p.particle_size_mm)):
                gd = x.el(x.el(sa, "gradingData"), "Grading", gml_id=_id("gd", hid, _num(g.depth_ft, 2), j))
                x.el(gd, "particleSize", _num(p.particle_size_mm, 4), uom="mm")
                x.el(gd, "sieveNumber", "")
                x.el(gd, "percentPassing", _num(p.percent_passing, 2), uom="%")
        for r in rows:
            d = _num(r.depth_top_ft, 2)
            if r.ll is not None or r.pl is not None or r.pi is not None:
                _simple_test(x, meas_root, proj_id, bid, lsr, hid, "ATTERBERG", "Atterberg", d, r.depth_bottom_ft,
                             [("Liquid Limit", "liquid_limit", "integer", r.ll), ("Plastic Limit", "plastic_limit", "integer", r.pl),
                              ("Plasticity Index", "plasticity_index", "integer", r.pi)])
            if r.wc is not None:
                _simple_test(x, meas_root, proj_id, bid, lsr, hid, "WATER CONTENT", "WaterContent", d, None,
                             [("Water Content", "water_content", "double", r.wc)])
            if r.hp_tsf is not None or r.odot_class:
                gi = r.group_index
                lab = r.odot_class if gi and gi.upper() != "V" else None
                vis = r.odot_class if not lab else None
                _simple_test(x, meas_root, proj_id, bid, lsr, hid, "POCKET PEN", "PocketPen", d, r.depth_bottom_ft,
                             [("Pocket penetrometer", "lab_penetrometer_measurement", "double", r.hp_text or r.hp_tsf),
                              ("Visual classification", "visual_classification", "string", vis),
                              ("Lab classification", "lab_classification", "string", lab),
                              ("Group index", "group_index", "string", None if (gi or "").upper() == "V" else gi)])
    return ET.ElementTree(root)


def _simple_test(x, root, proj_id, bid, lsr, hid, name, prefix, depth, bottom, props):
    t = x.el(root, "Test", gml_id=_id(prefix, hid, depth))
    x.gml(t, "name", name)
    x.el(t, "investigationTarget", "Natural Ground")
    x.ref(t, "projectRef", proj_id)
    x.ref(t, "samplingFeatureRef", bid)
    tr = x.el(x.el(t, "outcome"), "TestResult", gml_id=_id("tr", hid, prefix, depth))
    le = x.el(x.el(tr, "location"), "LinearExtent", gml_id=_id("trl", hid, prefix, depth), srsDimension=1, srsName=f"#{lsr}")
    x.gml(le, "posList", depth if bottom is None else f"{depth} {_num(bottom, 2)}")
    rs = x.el(x.el(tr, "results"), "ResultSet")
    pp = x.el(x.el(rs, "parameters"), "PropertyParameters", gml_id=_id("pp", hid, prefix, depth))
    props_el = x.el(pp, "properties")
    vals = []
    for j, (pname, pclass, ptype, val) in enumerate(props):
        p = x.el(props_el, "Property", gml_id=_id("prop", hid, prefix, depth, j), index=j)
        x.el(p, "propertyName", pname)
        x.el(p, "typeData", ptype)
        x.el(p, "propertyClass", pclass, codeSpace=PROPERTY_CS)
        x.el(p, "uom", "%" if ptype != "string" else "")
        vals.append("" if val is None else (f"{val:g}" if isinstance(val, (int, float)) else str(val)))
    x.el(rs, "dataValues", ",".join(vals), cs=",", ts=" ", decimal=".")


def write_diggs(holes, path, **kw) -> Path:
    """Write ``holes`` (Borehole objects or BoringLog-like objects with
    ``to_borehole``) to ``path`` as DIGGS XML; returns the path."""
    tree = build_diggs(holes, **kw)
    ET.indent(tree, space="\t")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tree.write(str(path), encoding="utf-8", xml_declaration=True)
    return path
